python 3.10 suppport, minor  changes
USEPA/WNTR pull request #287
Opened 2022-08-18 13:32 UTC by Thaulino

Good day everyone, 

What i have done: 
Added minimal build system spec pyproject.toml -> https://peps.python.org/pep-0518/ -> this will also install numpy before running setup.py 
Insert a check in setup.py if python version >= 3.10, if true the extensions are freshly built
As i wanted to test if this works on a virgin system, i added  a docker file for testing installation procedure within virgin ubuntu system.

Will solve #254 
Looking forward for a review

kind regards

2022-08-18 13:47 UTC, Thaulino commented
upps somehow the tests are not running -.-

2022-08-18 17:54 UTC, Thaulino commented
According to this: https://nose.readthedocs.io/en/latest/
nose is in maintenance mode and has no active maintainer

nose2 or pytest may be a sufficient replacement

2022-08-18 17:56 UTC, Thaulino commented
As supporting python 3.10 seems to have more implications as expected i converted the pull request to a draft.

2022-08-18 21:01 UTC, kaklise commented
@Thaulino Thanks for working on Python 3.10 support! I'll take a look at the test failures and see if we can get this working.

2022-08-19 13:21 UTC, michaelbynum commented
To support python 3.10, we have to switch from nose to pytest.

2022-08-19 13:25 UTC, michaelbynum commented
My mistake. It looks like you are already doing that. Nose is causing the test failures though. It looks like nose is still referenced in `build_tests.yml`.

2022-08-19 15:26 UTC, Thaulino commented
@michaelbynum  thanks for your review, indeed i am replacing nose with pytest allready, i am Just partly finished but the quicktest allready works 😁

2022-08-19 15:27 UTC, michaelbynum commented
That's great! As @kaklise said, thanks for the contribution!

2022-08-22 12:54 UTC, Thaulino commented
@kaklise 
@michaelbynum 

Hi everyone, i refactored the workflows and more for a better readability, a from my point of view more phytonic way of distributing the package and of course python 3.10 support. 

Regarding the more phytonic way of distributing the package
I noticed that the wntr package currently ships with prebuild extensions (for example sim / network_isolation) and a wheel valid for all platforms, refer to https://pypi.org/project/wntr/#files
The corresponding wheel on pypi is a pure python wheel. 
This is a little bit in conflict with the wntr package content as it has c/c++ extensions which are depending on plattforms python version and ... 

I would suggest to delete all the prebuild stuff and upload only the source files and a wheel file for every os / python version you want to support. All other combinations have to built the package from source. This way it is granted that if the installation via pip succeeds the wntr package is working.
This would solve issues like #259, #276

kind regards

2022-08-22 15:10 UTC, kaklise commented
@Thaulino Thanks for continuing to work on this.  
@michaelbynum @dbhart Can you please review the changes in this PR?

2022-08-26 07:57 UTC, Thaulino commented
hi guys, 
any progress reviewing the PR ?
can i help you with something ? 

kind regards

2022-08-26 15:36 UTC, kaklise commented
@Thaulino Thanks for checking in.  We plan to review the PR next week.

2022-08-29 17:52 UTC, dbhart requested changes
Hi @Thaulino 
We've looked over this and I do have a couple comments. We would prefer that the docker files not be included in the commit, since they are only used for local development as opposed to use in the actions.

The other thing is that we do need to keep the _evaluator and _network_isolation binaries included in the repository. These almost never change, other than being updated for new versions of Python (they haven't changed since before 3.9 was a thing, maybe since before 3.8, because I remember having to get them built to be added in). 

We are aware that this technically isn't best practice, but we have a use case where people are using WNTR in development mode but do not have access to C++ compilers installed on their machines. So they pull in or make changes to Python files elsewhere in the package, but can't build the aml/network_isolation plugins themselves, so we need them in the repository. 

With your updates here, we would then take the artifacts of the build and add in py310 support as well once we pull in the PR. If we were just doing PyPI, we could do just wheel upload, but our use cases don't allow for that. Right now we are thinking of putting in a flag, like what you had for the 3.10 in setup.py, that would only set build to true in the GitHub workflow, and be false by default when pulling from the repository. Hopefully that all makes sense.

I think if you can exclude the dockerfile pieces and undelete the binaries, we would be ready to pull this in. I am currently going through the test_examples to try to figure out why they aren't working, so that we don't have to exclude them, but I don't think we need to wait for that :-)

@kaklise anything else?

2022-08-29 19:39 UTC, Thaulino commented
Please ignore the last 2 commits, i used the wrong branch -> reverted all changes

2022-08-29 20:01 UTC, Thaulino commented
@dbhart  thanks for the the feedback and the detailed explanation. 
It makes some sense to me :wink:  
Even though i would handle this like i described it allready 
--- proposal starting ---- 
keep the package as pythonic as possible, maybe adding a how-to-dev section to the documentation.
Describe the process of setting up a dev environment: install requirements for python, install C/C++ Toolchain and so on.
I think at the end 2 of the 3 major plattforms allready have a C/C++ toolchain preinstalled or it is a one liner like  `brew install gcc` 
As a reference: what the numpy community wrote: 
https://numpy.org/doc/stable/dev/development_environment.html
--- proposal ending ---- 
i understand your arguments as well and in the end, it is up to you :smile: 

I have excluded the docker files and inlcuded the binaries again 

kind regards

2022-08-29 20:18 UTC, Thaulino commented
hmm, that is strange i restarted the workflow on my fork (same hash) and it succeeded. 
https://github.com/Thaulino/WNTR/actions/runs/2951244882 
https://github.com/Thaulino/WNTR/actions/runs/2951244877 
Can you try restart the workflow with enabled debug logs ? 
I cannot restart the workflow in your repository :frowning_face:

2022-08-29 20:35 UTC, Thaulino commented
Renamed the test marker: time_consuming (because the marked tests are time consuming) 
Enabled time consuming tests for build tests refer -> #289

2022-08-29 21:00 UTC, Thaulino commented
Hooray, all tests succeeded 

but i do not understand why this one does not succeded: 
https://github.com/USEPA/WNTR/pull/287/checks?check_run_id=8078470097 
do we have a  workflow issue ? 
We should keep that in mind.

2022-08-31 19:24 UTC, Thaulino commented
@kaklise @dbhart  any thougths ? Can i Help ?

Kind regards

2022-09-06 13:55 UTC, dbhart commented
Hi @thi, I am working on going through all of it! Thanks!
________________________________
From: Thi ***@***.***>
Sent: Wednesday, August 31, 2022 1:24:12 PM
To: USEPA/WNTR ***@***.***>
Cc: Hart, David Blaine ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [USEPA/WNTR] python 3.10 suppport (PR #287)


@kaklise<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaklise&data=05%7C01%7Cdbhart%40sandia.gov%7C3442babca22f4ad6a97f08da8b866443%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637975706567637209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4SAEMwIWU40Jy6%2BPs4TwjGBfKxt1QvVIN6py0p9SYtM%3D&reserved=0> @dbhart<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbhart&data=05%7C01%7Cdbhart%40sandia.gov%7C3442babca22f4ad6a97f08da8b866443%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637975706567637209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BMGgtB8e424ryXcgbRhhglPipWM0Fa7fJ4a3wQdsewQ%3D&reserved=0> any thougths ? Can i Help ?

Kind regards

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSEPA%2FWNTR%2Fpull%2F287%23issuecomment-1233333035&data=05%7C01%7Cdbhart%40sandia.gov%7C3442babca22f4ad6a97f08da8b866443%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637975706567793448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JEk3RIpiWtjQ8yAvKGyDL3%2FxpiiHatvVniF%2FPUUcETo%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABKDSSO7VHWPCXKB2PXRG6LV36WNZANCNFSM565HJCKQ&data=05%7C01%7Cdbhart%40sandia.gov%7C3442babca22f4ad6a97f08da8b866443%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637975706567793448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KzyPOBMCbDEsLk77LdTNJBoLKmcjTpFYHVvTuViSFKo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-06 16:20 UTC, dbhart approved these changes
These look good. @kaklise I think we can merge this in, then I'll add in the DLLs for py 310.

2022-09-06 19:17 UTC, merged