add function for reverse links direction
USEPA/WNTR pull request #368
Opened 2023-08-13 10:19 UTC by GalPerelman

This PR adds a function that can reverse links direction
The function preserves the link's vertices

2023-10-09 14:10 UTC, kbonney requested changes

2023-10-10 06:19 UTC, GalPerelman commented on wntr/morph/link.py
> +def reverse_link(wn: wntr.network.WaterNetworkModel, link_name: str) -> wntr.network.WaterNetworkModel:
@kbonney 
Sorry for the late response, for some reason I missed your comments
Yes, I will update the PR soon

2023-10-10 13:27 UTC, kbonney commented on wntr/morph/link.py
> +def reverse_link(wn: wntr.network.WaterNetworkModel, link_name: str) -> wntr.network.WaterNetworkModel:
@GalPerelman, I think I missed the "submit review" button so the notifications only went through recently. Thanks!

2023-10-12 08:04 UTC, GalPerelman commented
@kbonney
I updated the PR with the minor changes but now one of the tests is failing
I couldn't figure out why this is happening, can you please help with this?

2023-10-12 13:15 UTC, kbonney commented
Thanks for resolving those issues.
These errors show up on occasion. It doesn't have anything to do with your code. @kaklise if we rerun the tests it should clear the failures and we can pull the updates in.

2023-10-13 23:31 UTC, merged